export default {
  key: 'adjektive',
  label: { de: 'Wichtige Adjektive', en: 'Key adjectives' },
  icon: '\u{1F3A8}',
  payoff: {
    de: 'Beschreiben und vergleichen - genau das verlangt die Präsentation.',
    en: 'Describing and comparing - exactly what the presentation asks for.',
  },

  adjectives: [
    ['ähnlich', null, 'similar', 'Die beiden Angebote sind sich sehr ähnlich.', 'The two offers are very similar to each other.'],
    ['angenehm', null, 'pleasant', 'Die Temperatur war angenehm.', 'The temperature was pleasant.'],
    ['ausreichend', null, 'sufficient', 'Zwei Stunden sind ausreichend.', 'Two hours are sufficient.'],
    ['beliebt', null, 'popular', 'Dieses Viertel ist bei Familien beliebt.', 'This district is popular with families.'],
    ['bequem', null, 'comfortable', 'Die Schuhe sind bequem und leicht.', 'The shoes are comfortable and light.'],
    ['besonders', null, 'special, particular', 'Das war ein besonderer Tag.', 'That was a special day.'],
    ['bestimmt', null, 'certain, definite', 'Zu bestimmten Zeiten ist es sehr voll.', 'At certain times it is very crowded.'],
    ['dringend', null, 'urgent', 'Ich brauche dringend einen Termin.', 'I urgently need an appointment.'],
    ['einfach', null, 'simple, easy', 'Die Anleitung ist einfach zu verstehen.', 'The instructions are easy to understand.'],
    ['endgültig', null, 'final', 'Das ist meine endgültige Antwort.', 'That is my final answer.'],
    ['ernst', null, 'serious', 'Er machte ein ernstes Gesicht.', 'He made a serious face.'],
    ['falsch', null, 'wrong', 'Ich habe die falsche Zeile angekreuzt.', 'I ticked the wrong line.'],
    ['fest', null, 'firm, fixed, permanent', 'Ich habe eine feste Stelle.', 'I have a permanent position.'],
    ['gefährlich', null, 'dangerous', 'Die Kreuzung ist für Radfahrer gefährlich.', 'The junction is dangerous for cyclists.'],
    ['genau', null, 'exact, precise', 'Nenne bitte die genaue Uhrzeit.', 'Please give the exact time.'],
    ['gewöhnlich', null, 'usual, ordinary', 'Wie gewöhnlich kam er zu spät.', 'As usual he came late.'],
    ['gleich', null, 'same, equal', 'Wir haben die gleichen Interessen.', 'We have the same interests.'],
    ['gründlich', null, 'thorough', 'Er arbeitet langsam, aber gründlich.', 'He works slowly but thoroughly.'],
    ['häufig', null, 'frequent', 'Das ist ein häufiger Fehler.', 'That is a frequent mistake.'],
    ['hilfreich', null, 'helpful', 'Dein Tipp war sehr hilfreich.', 'Your tip was very helpful.'],
    ['komplett', null, 'complete', 'Der Satz ist komplett anders.', 'The sentence is completely different.'],
    ['kompliziert', null, 'complicated', 'Das Formular ist unnötig kompliziert.', 'The form is unnecessarily complicated.'],
    ['kürzlich', null, 'recent(ly)', 'Kürzlich habe ich davon gehört.', 'Recently I heard about it.'],
    ['möglich', null, 'possible', 'Eine Rückgabe ist bis Freitag möglich.', 'A return is possible until Friday.'],
    ['nötig', null, 'necessary', 'Mehr ist nicht nötig.', 'More is not necessary.'],
    ['normal', null, 'normal', 'Das ist bei uns völlig normal.', 'That is completely normal here.'],
    ['nützlich', null, 'useful', 'Die App ist wirklich nützlich.', 'The app is really useful.'],
    ['offen', null, 'open', 'Ich bin für Vorschläge offen.', 'I am open to suggestions.'],
    ['peinlich', null, 'embarrassing', 'Der Fehler war mir peinlich.', 'The mistake was embarrassing for me.'],
    ['plötzlich', null, 'sudden', 'Ein plötzlicher Regen hat alles nass gemacht.', 'A sudden shower soaked everything.'],
    ['schlimm', null, 'bad, serious', 'So schlimm war es gar nicht.', 'It was not that bad at all.'],
    ['selten', null, 'rare', 'Solche Angebote sind selten.', 'Such offers are rare.'],
    ['sicher', null, 'safe, certain', 'Hier ist es auch nachts sicher.', 'It is safe here even at night.'],
    ['üblich', null, 'customary', 'Trinkgeld ist hier üblich.', 'A tip is customary here.'],
    ['unbedingt', null, 'absolute(ly), by all means', 'Du solltest unbedingt hingehen.', 'You should definitely go.'],
    ['ungefähr', null, 'approximate(ly)', 'Die Fahrt dauert ungefähr eine Stunde.', 'The journey takes approximately an hour.'],
    ['verschieden', null, 'different, various', 'Es gibt verschiedene Möglichkeiten.', 'There are various possibilities.'],
    ['vorsichtig', null, 'careful', 'Sei vorsichtig mit dem heißen Blech.', 'Be careful with the hot tray.'],
    ['wahrscheinlich', null, 'probable, probably', 'Wahrscheinlich komme ich erst um acht.', 'I will probably only get there at eight.'],
    ['wichtig', null, 'important', 'Das Wichtigste ist die Aussprache.', 'The most important thing is pronunciation.'],
    ['zusätzlich', null, 'additional', 'Für zusätzliche Kosten kommt die Firma auf.', 'The company covers additional costs.'],
    ['ausgezeichnet', null, 'excellent', 'Das Essen war ausgezeichnet.', 'The food was excellent.'],
    ['erfolgreich', null, 'successful', 'Die Aktion war sehr erfolgreich.', 'The campaign was very successful.'],
  ],
};
