export default {
  key: 'arbeit',
  label: { de: 'Arbeit & Beruf', en: 'Work & career' },
  icon: '\u{1F4BC}',
  payoff: {
    de: 'Schreiben Teil 3 (formelle Mail) und Lesen Teil 4: Bewerbung, Chef, Kollegen.',
    en: 'Schreiben part 3 (formal email) and Lesen part 4: applications, bosses, colleagues.',
  },

  nouns: [
    ['der Beruf', '-e', 'profession, occupation', 'Von Beruf bin ich Krankenpfleger.', 'By profession I am a nurse.'],
    ['die Ausbildung', '-en', 'vocational training', 'Die Ausbildung dauert drei Jahre.', 'The training takes three years.'],
    ['die Bewerbung', '-en', 'application', 'Die Bewerbung schicke ich heute noch ab.', 'I am sending off the application today.'],
    ['der Lebenslauf', '-¨e', 'CV, résumé', 'Der Lebenslauf sollte höchstens zwei Seiten haben.', 'The CV should be two pages at most.'],
    ['das Zeugnis', '-se', 'certificate, reference', 'Mein Zeugnis ist aus dem Ausland und wurde anerkannt.', 'My certificate is from abroad and was recognised.'],
    ['das Vorstellungsgespräch', '-e', 'job interview', 'Das Vorstellungsgespräch ist am Dienstag um zehn.', 'The job interview is on Tuesday at ten.'],
    ['der Arbeitgeber', '-', 'employer', 'Mein Arbeitgeber zahlt die Fahrkarte.', 'My employer pays for the travel ticket.'],
    ['der Arbeitnehmer', '-', 'employee', 'Jeder Arbeitnehmer hat Anspruch auf Urlaub.', 'Every employee is entitled to holiday.'],
    ['der Vertrag', '-¨e', 'contract', 'Mein Vertrag ist bis Ende des Jahres befristet.', 'My contract is limited until the end of the year.'],
    ['das Gehalt', '-¨er', 'salary', 'Über das Gehalt sprechen wir im zweiten Gespräch.', 'We will talk about the salary in the second interview.'],
    ['der Lohn', '-¨e', 'wage, pay', 'Der Lohn wird stündlich abgerechnet.', 'The pay is calculated by the hour.'],
    ['die Arbeitszeit', '-en', 'working hours', 'Meine Arbeitszeit ist von acht bis halb fünf.', 'My working hours are from eight to half past four.'],
    ['die Schicht', '-en', 'shift', 'Diese Woche habe ich Nachtschicht.', 'This week I am on the night shift.'],
    ['die Überstunde', '-n', 'overtime hour', 'Überstunden werden mit Freizeit ausgeglichen.', 'Overtime is compensated with time off.'],
    ['der Urlaub', '-e', 'holiday, leave', 'Ich habe noch zwölf Tage Urlaub übrig.', 'I still have twelve days of leave left.'],
    ['die Stelle', '-n', 'position, job', 'Die Stelle ist ab sofort zu besetzen.', 'The position is to be filled immediately.'],
    ['die Abteilung', '-en', 'department', 'Ich arbeite in der Abteilung Einkauf.', 'I work in the purchasing department.'],
    ['der Chef', '-s', 'boss', 'Mein Chef ist streng, aber fair.', 'My boss is strict but fair.'],
    ['die Besprechung', '-en', 'meeting', 'Die Besprechung wurde auf Freitag verschoben.', 'The meeting was postponed to Friday.'],
    ['die Erfahrung', '-en', 'experience', 'Ich habe fünf Jahre Erfahrung in der Pflege.', 'I have five years of experience in nursing.'],
    ['die Fortbildung', '-en', 'further training', 'Die Firma bezahlt eine Fortbildung pro Jahr.', 'The company pays for one training course a year.'],
    ['die Arbeitslosigkeit', 'ohne Plural', 'unemployment', 'Die Arbeitslosigkeit ist in der Region gesunken.', 'Unemployment has fallen in the region.'],
    ['der Betriebsrat', '-¨e', 'works council', 'Bei Problemen hilft der Betriebsrat.', 'If there are problems the works council helps.'],
    ['die Probezeit', '-en', 'probation period', 'In der Probezeit kann man kurzfristig kündigen.', 'During the probation period notice can be short.'],
  ],

  verbs: [
    ['sich bewerben', 'bewirbt sich · bewarb sich · hat sich beworben', 'to apply', 'Ich bewerbe mich auf die Stelle als Fahrer.', 'I am applying for the position as a driver.'],
    ['einstellen', null, 'to hire, to take on', 'Die Firma stellt im Frühjahr zwanzig Leute ein.', 'The company is hiring twenty people in the spring.'],
    ['verdienen', null, 'to earn', 'Sie verdient genug, um die Miete zu zahlen.', 'She earns enough to pay the rent.'],
    ['leiten', null, 'to lead, to manage', 'Er leitet ein Team von acht Personen.', 'He leads a team of eight people.'],
    ['sich melden', null, 'to get in touch', 'Wir melden uns bis Ende der Woche bei Ihnen.', 'We will get in touch with you by the end of the week.'],
    ['erledigen', null, 'to deal with, to get done', 'Die Aufgabe habe ich schon erledigt.', 'I have already dealt with the task.'],
    ['sich weiterbilden', null, 'to do further training', 'Neben der Arbeit bilde ich mich weiter.', 'Alongside work I am doing further training.'],
    ['verhandeln', null, 'to negotiate', 'Über das Gehalt lässt sich verhandeln.', 'The salary is negotiable.'],
    ['beantragen', null, 'to apply for (formally)', 'Ich habe Urlaub für die zweite Juniwoche beantragt.', 'I applied for leave for the second week of June.'],
    ['einreichen', null, 'to submit, to hand in', 'Reichen Sie die Unterlagen bis Freitag ein.', 'Please submit the documents by Friday.'],
    ['sich krankmelden', null, 'to call in sick', 'Bei Grippe muss man sich sofort krankmelden.', 'With flu you must call in sick straight away.'],
    ['anerkennen', 'erkennt an · erkannte an · hat anerkannt', 'to recognise (a qualification)', 'Mein Abschluss wurde in Deutschland anerkannt.', 'My degree was recognised in Germany.'],
  ],

  adjectives: [
    ['berufstätig', null, 'in employment, working', 'Beide Elternteile sind berufstätig.', 'Both parents are in employment.'],
    ['selbstständig', null, 'self-employed, independent', 'Seit zwei Jahren bin ich selbstständig.', 'I have been self-employed for two years.'],
    ['arbeitslos', null, 'unemployed', 'Nach der Insolvenz war er kurz arbeitslos.', 'After the insolvency he was briefly unemployed.'],
    ['befristet', null, 'fixed-term', 'Der Vertrag ist auf ein Jahr befristet.', 'The contract is fixed-term for one year.'],
    ['zuständig', null, 'responsible, in charge', 'Für Beschwerden ist Frau Yildiz zuständig.', 'Ms Yildiz is responsible for complaints.'],
    ['pünktlich', null, 'punctual', 'In der Probezeit solltest du besonders pünktlich sein.', 'During probation you should be especially punctual.'],
    ['anstrengend', null, 'demanding, tiring', 'Die Schicht war lang und anstrengend.', 'The shift was long and tiring.'],
    ['qualifiziert', null, 'qualified', 'Wir suchen qualifizierte Fachkräfte.', 'We are looking for qualified specialists.'],
  ],

  phrases: [
    ['Bescheid sagen', null, 'to let someone know', 'Sag bitte Bescheid, wenn du später kommst.', 'Please let me know if you are coming later.'],
    ['eine Stelle antreten', null, 'to start a job', 'Die Stelle trete ich am ersten Oktober an.', 'I am starting the job on the first of October.'],
    ['im Schichtdienst arbeiten', null, 'to work shifts', 'Im Krankenhaus arbeite ich im Schichtdienst.', 'At the hospital I work shifts.'],
    ['Wert legen auf', null, 'to attach importance to', 'Unsere Firma legt Wert auf Pünktlichkeit.', 'Our company attaches importance to punctuality.'],
  ],
};
