export default {
  key: 'bildung',
  label: { de: 'Bildung & Lernen', en: 'Education & learning' },
  icon: '\u{1F393}',
  payoff: {
    de: 'Hören Teil 2 (Vortrag) und Sprechen: Kurse, Schule, Weiterbildung.',
    en: 'Hören part 2 (a talk) and Sprechen: courses, school, further training.',
  },

  nouns: [
    ['die Bildung', 'ohne Plural', 'education', 'Bildung ist in Deutschland Ländersache.', 'Education is a matter for the federal states in Germany.'],
    ['die Schule', '-n', 'school', 'Die Schule beginnt um Viertel vor acht.', 'School starts at quarter to eight.'],
    ['der Unterricht', 'ohne Plural', 'lessons, teaching', 'Der Unterricht fällt heute aus.', 'The lesson is cancelled today.'],
    ['das Fach', '-¨er', 'subject', 'Mein liebstes Fach war Erdkunde.', 'My favourite subject was geography.'],
    ['die Note', '-n', 'grade, mark', 'Mit der Note bin ich sehr zufrieden.', 'I am very happy with the grade.'],
    ['die Prüfung', '-en', 'exam', 'Die Prüfung besteht aus vier Teilen.', 'The exam consists of four parts.'],
    ['der Abschluss', '-¨e', 'qualification, degree', 'Ohne Abschluss ist die Stellensuche schwer.', 'Without a qualification the job search is hard.'],
    ['das Studium', 'Studien', 'university studies', 'Ihr Studium hat sechs Semester gedauert.', 'Her studies took six semesters.'],
    ['die Universität', '-en', 'university', 'Die Universität liegt am Stadtrand.', 'The university is on the edge of town.'],
    ['der Kurs', '-e', 'course', 'Der Kurs findet zweimal pro Woche statt.', 'The course takes place twice a week.'],
    ['die Volkshochschule', '-n', 'adult education centre', 'An der Volkshochschule kosten Sprachkurse wenig.', 'At the adult education centre language courses cost little.'],
    ['der Integrationskurs', '-e', 'integration course', 'Der Integrationskurs endet mit dem DTZ.', 'The integration course ends with the DTZ exam.'],
    ['die Hausaufgabe', '-n', 'homework', 'Die Hausaufgaben mache ich abends.', 'I do my homework in the evenings.'],
    ['der Lehrer', '-', 'teacher', 'Unser Lehrer spricht sehr deutlich.', 'Our teacher speaks very clearly.'],
    ['der Schüler', '-', 'pupil', 'In der Klasse sind 24 Schüler.', 'There are 24 pupils in the class.'],
    ['der Teilnehmer', '-', 'participant', 'Alle Teilnehmer bekommen ein Zertifikat.', 'All participants receive a certificate.'],
    ['das Wissen', 'ohne Plural', 'knowledge', 'Ihr Wissen über Grammatik ist beeindruckend.', 'Her knowledge of grammar is impressive.'],
    ['die Kenntnis', '-se', 'knowledge, command (of)', 'Für die Stelle sind Deutschkenntnisse auf B1 nötig.', 'The position requires German at B1 level.'],
    ['der Fehler', '-', 'mistake', 'Aus Fehlern lernt man am meisten.', 'You learn most from mistakes.'],
    ['die Aufgabe', '-n', 'task, exercise', 'Lesen Sie die Aufgabe zweimal.', 'Read the task twice.'],
    ['das Ergebnis', '-se', 'result', 'Das Ergebnis kommt in zwei Wochen per Post.', 'The result comes by post in two weeks.'],
    ['die Anmeldung', '-en', 'registration, enrolment', 'Die Anmeldung ist bis zum 15. März möglich.', 'Enrolment is possible until 15 March.'],
    ['die Gebühr', '-en', 'fee', 'Die Gebühr für die Prüfung beträgt 150 Euro.', 'The fee for the exam is 150 euros.'],
    ['der Fortschritt', '-e', 'progress', 'Nach drei Monaten sieht man deutliche Fortschritte.', 'After three months you can see clear progress.'],
  ],

  verbs: [
    ['lernen', null, 'to learn, to study', 'Ich lerne jeden Abend zwanzig neue Wörter.', 'I learn twenty new words every evening.'],
    ['studieren', null, 'to study (at university)', 'Sie studiert Medizin in Heidelberg.', 'She is studying medicine in Heidelberg.'],
    ['unterrichten', null, 'to teach', 'Er unterrichtet Deutsch als Fremdsprache.', 'He teaches German as a foreign language.'],
    ['bestehen', 'besteht · bestand · hat bestanden', 'to pass (an exam)', 'Ich habe die Prüfung im zweiten Versuch bestanden.', 'I passed the exam on the second attempt.'],
    ['durchfallen', 'fällt durch · fiel durch · ist durchgefallen', 'to fail (an exam)', 'Beim ersten Mal bin ich knapp durchgefallen.', 'The first time I narrowly failed.'],
    ['wiederholen', null, 'to repeat, to revise', 'Wiederhol die Vokabeln vor dem Schlafen.', 'Revise the vocabulary before going to sleep.'],
    ['erklären', null, 'to explain', 'Können Sie das bitte noch einmal erklären?', 'Could you explain that once more, please?'],
    ['verstehen', 'versteht · verstand · hat verstanden', 'to understand', 'Den zweiten Teil habe ich nicht ganz verstanden.', 'I did not quite understand the second part.'],
    ['sich anmelden', null, 'to register, to enrol', 'Für den Kurs musst du dich online anmelden.', 'You have to enrol for the course online.'],
    ['sich vorbereiten', null, 'to prepare', 'Ich bereite mich seit Januar auf die Prüfung vor.', 'I have been preparing for the exam since January.'],
    ['üben', null, 'to practise', 'Sprechen übe ich mit einer Kollegin.', 'I practise speaking with a colleague.'],
    ['teilnehmen', 'nimmt teil · nahm teil · hat teilgenommen', 'to take part', 'An dem Workshop nehmen zwölf Leute teil.', 'Twelve people are taking part in the workshop.'],
    ['sich merken', null, 'to memorise, to remember', 'Diese Regel kann ich mir einfach nicht merken.', 'I simply cannot remember this rule.'],
    ['nachschlagen', 'schlägt nach · schlug nach · hat nachgeschlagen', 'to look up', 'Unbekannte Wörter schlage ich im Wörterbuch nach.', 'I look up unknown words in the dictionary.'],
  ],

  adjectives: [
    ['schwierig', null, 'difficult', 'Der Hörteil ist für mich am schwierigsten.', 'The listening part is the most difficult for me.'],
    ['kostenlos', null, 'free of charge', 'Der erste Beratungstermin ist kostenlos.', 'The first advice appointment is free.'],
    ['verpflichtend', null, 'compulsory', 'Die Teilnahme ist verpflichtend.', 'Participation is compulsory.'],
    ['praktisch', null, 'practical, handy', 'Der praktische Teil hat mir mehr gebracht.', 'The practical part was more use to me.'],
    ['theoretisch', null, 'theoretical', 'Theoretisch weiß ich es, praktisch nicht.', 'In theory I know it, in practice I do not.'],
    ['begabt', null, 'talented', 'Sie ist sprachlich sehr begabt.', 'She is very talented at languages.'],
    ['aufmerksam', null, 'attentive', 'Hören Sie aufmerksam zu.', 'Listen attentively.'],
  ],

  phrases: [
    ['einen Kurs besuchen', null, 'to attend a course', 'Abends besuche ich einen Kurs an der VHS.', 'In the evenings I attend a course at the adult education centre.'],
    ['eine Prüfung ablegen', null, 'to sit an exam', 'Die Prüfung lege ich im Juni ab.', 'I am sitting the exam in June.'],
    ['Fortschritte machen', null, 'to make progress', 'Beim Sprechen mache ich langsam Fortschritte.', 'I am slowly making progress with speaking.'],
    ['Schritt für Schritt', null, 'step by step', 'Schritt für Schritt wird es leichter.', 'Step by step it gets easier.'],
  ],
};
