export default {
  key: 'einkaufen',
  label: { de: 'Einkaufen & Geld', en: 'Shopping & money' },
  icon: '\u{1F6D2}',
  payoff: {
    de: 'Schreiben Teil 3: Beschwerde, Umtausch, Reklamation an eine Firma.',
    en: 'Schreiben part 3: complaints, exchanges and returns to a company.',
  },

  nouns: [
    ['das Geschäft', '-e', 'shop, business', 'Das Geschäft an der Ecke hat bis 22 Uhr offen.', 'The shop on the corner is open until 10 p.m.'],
    ['der Kunde', '-n', 'customer', 'Der Kunde hat Anspruch auf eine Quittung.', 'The customer is entitled to a receipt.'],
    ['die Kasse', '-n', 'till, checkout', 'An Kasse drei ist weniger los.', 'There is less going on at till three.'],
    ['die Quittung', '-en', 'receipt', 'Ohne Quittung ist ein Umtausch schwierig.', 'Without a receipt an exchange is difficult.'],
    ['der Kassenbon', '-s', 'till receipt', 'Bitte bewahren Sie den Kassenbon auf.', 'Please keep the till receipt.'],
    ['der Preis', '-e', 'price', 'Der Preis ist im Internet deutlich niedriger.', 'The price is considerably lower online.'],
    ['das Angebot', '-e', 'offer, special', 'Diese Woche ist Kaffee im Angebot.', 'This week coffee is on special offer.'],
    ['der Rabatt', '-e', 'discount', 'Auf alle Winterjacken gibt es 30 Prozent Rabatt.', 'There is 30 percent off all winter jackets.'],
    ['die Garantie', '-n', 'warranty', 'Auf das Gerät sind zwei Jahre Garantie.', 'The device has a two-year warranty.'],
    ['der Umtausch', 'ohne Plural', 'exchange (of goods)', 'Der Umtausch ist bis 14 Tage nach dem Kauf möglich.', 'An exchange is possible up to 14 days after purchase.'],
    ['die Reklamation', '-en', 'complaint (about goods)', 'Ich möchte eine Reklamation aufgeben.', 'I would like to make a complaint.'],
    ['die Lieferung', '-en', 'delivery', 'Die Lieferung kommt in drei bis fünf Werktagen.', 'The delivery comes in three to five working days.'],
    ['die Bestellung', '-en', 'order', 'Meine Bestellung ist bis heute nicht angekommen.', 'My order has not arrived to this day.'],
    ['das Bargeld', 'ohne Plural', 'cash', 'Auf dem Markt brauchst du Bargeld.', 'At the market you need cash.'],
    ['die Karte', '-n', 'card (bank, credit)', 'Kann ich mit Karte zahlen?', 'Can I pay by card?'],
    ['das Konto', 'Konten', 'bank account', 'Das Geld ist gestern auf dem Konto eingegangen.', 'The money arrived in the account yesterday.'],
    ['die Schulden', 'nur Plural', 'debts', 'Nach dem Umzug hatten wir kurz Schulden.', 'After the move we were briefly in debt.'],
    ['die Versicherung', '-en', 'insurance', 'Eine Haftpflichtversicherung hat hier fast jeder.', 'Almost everyone here has personal liability insurance.'],
    ['das Sonderangebot', '-e', 'special offer', 'Sonderangebote gelten nur solange der Vorrat reicht.', 'Special offers apply only while stocks last.'],
    ['die Öffnungszeiten', 'nur Plural', 'opening hours', 'Die Öffnungszeiten stehen an der Tür.', 'The opening hours are on the door.'],
  ],

  verbs: [
    ['einkaufen', null, 'to shop, to buy groceries', 'Samstags kaufe ich für die ganze Woche ein.', 'On Saturdays I shop for the whole week.'],
    ['umtauschen', null, 'to exchange', 'Die Schuhe möchte ich gern umtauschen.', 'I would like to exchange the shoes.'],
    ['zurückgeben', 'gibt zurück · gab zurück · hat zurückgegeben', 'to return (an item)', 'Innerhalb von 14 Tagen kann man alles zurückgeben.', 'Within 14 days you can return anything.'],
    ['sich beschweren', null, 'to complain', 'Ich habe mich schriftlich beschwert.', 'I complained in writing.'],
    ['reklamieren', null, 'to make a complaint about goods', 'Das defekte Gerät habe ich sofort reklamiert.', 'I complained about the faulty device immediately.'],
    ['bezahlen', null, 'to pay', 'Bezahlt wird an der Kasse vorne.', 'Payment is at the till at the front.'],
    ['sparen', null, 'to save (money)', 'Wir sparen für eine größere Wohnung.', 'We are saving for a bigger flat.'],
    ['ausgeben', 'gibt aus · gab aus · hat ausgegeben', 'to spend', 'Für Lebensmittel gebe ich 300 Euro im Monat aus.', 'I spend 300 euros a month on food.'],
    ['überweisen', 'überweist · überwies · hat überwiesen', 'to transfer (money)', 'Den Betrag überweise ich morgen.', 'I will transfer the amount tomorrow.'],
    ['abheben', 'hebt ab · hob ab · hat abgehoben', 'to withdraw (cash)', 'Am Automaten hebe ich 100 Euro ab.', 'I withdraw 100 euros at the cash machine.'],
    ['sich leisten', null, 'to afford', 'Ein Auto können wir uns gerade nicht leisten.', 'We cannot afford a car at the moment.'],
    ['liefern', null, 'to deliver', 'Der Laden liefert kostenlos ab 40 Euro.', 'The shop delivers free from 40 euros.'],
    ['vergleichen', 'vergleicht · verglich · hat verglichen', 'to compare', 'Vergleich die Preise, bevor du kaufst.', 'Compare the prices before you buy.'],
  ],

  adjectives: [
    ['teuer', null, 'expensive', 'Die Innenstadt ist mir zu teuer.', 'The city centre is too expensive for me.'],
    ['preiswert', null, 'good value', 'Das Angebot ist wirklich preiswert.', 'The offer is really good value.'],
    ['defekt', null, 'faulty, broken', 'Das Gerät kam schon defekt an.', 'The device already arrived faulty.'],
    ['gebraucht', null, 'second-hand', 'Das Fahrrad habe ich gebraucht gekauft.', 'I bought the bicycle second-hand.'],
    ['begrenzt', null, 'limited', 'Das Angebot ist zeitlich begrenzt.', 'The offer is limited in time.'],
    ['sparsam', null, 'thrifty, economical', 'Sie lebt sehr sparsam.', 'She lives very thriftily.'],
  ],

  phrases: [
    ['im Angebot sein', null, 'to be on offer', 'Diese Woche ist Käse im Angebot.', 'This week cheese is on offer.'],
    ['Geld überweisen', null, 'to transfer money', 'Ich überweise das Geld noch heute.', 'I will transfer the money today.'],
    ['in Raten zahlen', null, 'to pay in instalments', 'Die Waschmaschine zahle ich in Raten.', 'I am paying for the washing machine in instalments.'],
    ['auf Rechnung kaufen', null, 'to buy on account', 'Online kaufe ich am liebsten auf Rechnung.', 'Online I prefer to buy on account.'],
  ],
};
