export default {
  key: 'familie',
  label: { de: 'Familie & Menschen', en: 'Family & people' },
  icon: '\u{1F46A}',
  payoff: {
    de: 'Sprechen Teil 1 und Schreiben: über dich und deine Leute erzählen.',
    en: 'Sprechen part 1 and Schreiben: talking about yourself and your people.',
  },

  nouns: [
    ['die Familie', '-n', 'family', 'Meine Familie wohnt seit zehn Jahren in Leipzig.', 'My family has lived in Leipzig for ten years.'],
    ['die Eltern', 'nur Plural', 'parents', 'Meine Eltern rufen jeden Sonntag an.', 'My parents call every Sunday.'],
    ['die Geschwister', 'nur Plural', 'siblings', 'Ich habe zwei Geschwister, einen Bruder und eine Schwester.', 'I have two siblings, a brother and a sister.'],
    ['der Verwandte', '-n', 'relative', 'Zur Hochzeit kommen auch Verwandte aus der Türkei.', 'Relatives from Turkey are also coming to the wedding.'],
    ['die Ehe', '-n', 'marriage', 'Ihre Ehe hält seit dreißig Jahren.', 'Their marriage has lasted thirty years.'],
    ['der Ehepartner', '-', 'spouse', 'Mein Ehepartner arbeitet im Krankenhaus.', 'My spouse works at the hospital.'],
    ['die Hochzeit', '-en', 'wedding', 'Die Hochzeit findet im Juni statt.', 'The wedding takes place in June.'],
    ['die Scheidung', '-en', 'divorce', 'Nach der Scheidung ist sie umgezogen.', 'After the divorce she moved away.'],
    ['die Beziehung', '-en', 'relationship', 'Wir führen seit zwei Jahren eine Beziehung.', 'We have been in a relationship for two years.'],
    ['die Freundschaft', '-en', 'friendship', 'Unsere Freundschaft begann in der Schule.', 'Our friendship began at school.'],
    ['der Nachbar', '-n', 'neighbour', 'Der Nachbar gießt die Blumen, wenn wir weg sind.', 'The neighbour waters the plants when we are away.'],
    ['der Kollege', '-n', 'colleague', 'Ein Kollege hat mir bei der Bewerbung geholfen.', 'A colleague helped me with the application.'],
    ['das Kind', '-er', 'child', 'Das Kind geht nächstes Jahr in die Schule.', 'The child starts school next year.'],
    ['der Enkel', '-', 'grandchild, grandson', 'Meine Großmutter sieht ihre Enkel jeden Monat.', 'My grandmother sees her grandchildren every month.'],
    ['die Erziehung', 'ohne Plural', 'upbringing, parenting', 'Die Erziehung teilen wir uns zu gleichen Teilen.', 'We share the parenting equally.'],
    ['das Vertrauen', 'ohne Plural', 'trust', 'Ohne Vertrauen funktioniert keine Beziehung.', 'No relationship works without trust.'],
    ['der Streit', '-e', 'argument, quarrel', 'Der Streit war schnell wieder vorbei.', 'The argument was over again quickly.'],
    ['die Unterstützung', 'ohne Plural', 'support', 'Ich bin für eure Unterstützung sehr dankbar.', 'I am very grateful for your support.'],
    ['die Generation', '-en', 'generation', 'In unserem Haus leben drei Generationen.', 'Three generations live in our house.'],
    ['die Herkunft', 'ohne Plural', 'origin, background', 'Bei uns arbeiten Menschen ganz unterschiedlicher Herkunft.', 'People of very different backgrounds work with us.'],
    ['die Muttersprache', '-n', 'mother tongue', 'Meine Muttersprache ist Arabisch, aber ich träume auf Deutsch.', 'My mother tongue is Arabic, but I dream in German.'],
    ['der Erwachsene', '-n', 'adult', 'Für Erwachsene kostet der Kurs 80 Euro.', 'For adults the course costs 80 euros.'],
    ['die Jugend', 'ohne Plural', 'youth', 'In meiner Jugend habe ich viel Fußball gespielt.', 'In my youth I played a lot of football.'],
    ['das Alter', 'ohne Plural', 'age', 'Im Alter von sechs Jahren kam ich nach Deutschland.', 'At the age of six I came to Germany.'],
  ],

  verbs: [
    ['heiraten', null, 'to marry', 'Sie heiraten im Sommer in Hamburg.', 'They are getting married in Hamburg in the summer.'],
    ['sich scheiden lassen', 'lässt sich scheiden · ließ sich scheiden · hat sich scheiden lassen', 'to get divorced', 'Seine Eltern haben sich vor zehn Jahren scheiden lassen.', 'His parents got divorced ten years ago.'],
    ['erziehen', 'erzieht · erzog · hat erzogen', 'to raise, to bring up', 'Sie erzieht ihre Kinder zweisprachig.', 'She is raising her children bilingually.'],
    ['sich kümmern', null, 'to take care (of)', 'Am Wochenende kümmere ich mich um meine Großmutter.', 'At the weekend I take care of my grandmother.'],
    ['sich verstehen', 'versteht sich · verstand sich · hat sich verstanden', 'to get on (with someone)', 'Mit meinen Schwiegereltern verstehe ich mich gut.', 'I get on well with my parents-in-law.'],
    ['sich streiten', 'streitet sich · stritt sich · hat sich gestritten', 'to argue', 'Wir streiten uns selten, und nie lange.', 'We rarely argue, and never for long.'],
    ['sich verlieben', null, 'to fall in love', 'Sie hat sich in einen Kollegen verliebt.', 'She fell in love with a colleague.'],
    ['vertrauen', null, 'to trust', 'Ich vertraue ihr völlig.', 'I trust her completely.'],
    ['unterstützen', null, 'to support', 'Meine Familie hat mich beim Lernen unterstützt.', 'My family supported me while I was studying.'],
    ['aufwachsen', 'wächst auf · wuchs auf · ist aufgewachsen', 'to grow up', 'Ich bin auf dem Land aufgewachsen.', 'I grew up in the countryside.'],
    ['sich trennen', null, 'to separate, to split up', 'Nach fünf Jahren haben sie sich getrennt.', 'After five years they split up.'],
    ['kennenlernen', 'lernt kennen · lernte kennen · hat kennengelernt', 'to get to know, to meet', 'Wir haben uns im Sprachkurs kennengelernt.', 'We met in the language course.'],
    ['sich verlassen auf', 'verlässt sich · verließ sich · hat sich verlassen', 'to rely on', 'Auf meinen Bruder kann ich mich immer verlassen.', 'I can always rely on my brother.'],
  ],

  adjectives: [
    ['verheiratet', null, 'married', 'Ich bin seit acht Jahren verheiratet.', 'I have been married for eight years.'],
    ['ledig', null, 'single, unmarried', 'Im Formular musste ich "ledig" ankreuzen.', 'On the form I had to tick "single".'],
    ['geschieden', null, 'divorced', 'Meine Tante ist geschieden und lebt allein.', 'My aunt is divorced and lives alone.'],
    ['erwachsen', null, 'grown-up, adult', 'Ihre Kinder sind längst erwachsen.', 'Her children have long been grown up.'],
    ['streng', null, 'strict', 'Mein Vater war streng, aber gerecht.', 'My father was strict but fair.'],
    ['zuverlässig', null, 'reliable', 'Sie ist die zuverlässigste Person, die ich kenne.', 'She is the most reliable person I know.'],
    ['gemeinsam', null, 'joint, together', 'Wir haben eine gemeinsame Wohnung.', 'We have a shared flat.'],
    ['alleinerziehend', null, 'single-parent', 'Als alleinerziehende Mutter hat sie wenig Freizeit.', 'As a single mother she has little free time.'],
  ],

  phrases: [
    ['sich um jemanden kümmern', null, 'to look after someone', 'Wer kümmert sich um die Kinder, wenn du arbeitest?', 'Who looks after the children when you work?'],
    ['in Kontakt bleiben', null, 'to stay in touch', 'Wir sind nach dem Kurs in Kontakt geblieben.', 'We stayed in touch after the course.'],
    ['eine Familie gründen', null, 'to start a family', 'Mit dreißig wollten wir eine Familie gründen.', 'At thirty we wanted to start a family.'],
    ['jemandem nahestehen', null, 'to be close to someone', 'Meine Schwester steht mir sehr nahe.', 'I am very close to my sister.'],
  ],
};
