export default {
  key: 'gefuehle',
  label: { de: 'Gefühle & Charakter', en: 'Feelings & character' },
  icon: '\u{1F60A}',
  payoff: {
    de: 'Sprechen Teil 3 und Schreiben Teil 1: reagieren, trösten, sich freuen.',
    en: 'Sprechen part 3 and Schreiben part 1: reacting, consoling, being pleased.',
  },

  nouns: [
    ['das Gefühl', '-e', 'feeling', 'Ich hatte von Anfang an ein gutes Gefühl.', 'I had a good feeling from the start.'],
    ['die Stimmung', '-en', 'mood, atmosphere', 'Die Stimmung im Team ist gerade sehr gut.', 'The mood in the team is very good at the moment.'],
    ['die Freude', '-n', 'joy', 'Deine Nachricht hat mir große Freude gemacht.', 'Your message gave me great joy.'],
    ['die Angst', '-¨e', 'fear', 'Vor der Prüfung hatte ich große Angst.', 'I was very afraid before the exam.'],
    ['die Sorge', '-n', 'worry', 'Mach dir keine Sorgen, das wird schon.', 'Do not worry, it will be fine.'],
    ['der Ärger', 'ohne Plural', 'annoyance, trouble', 'Mit dem Vermieter gab es viel Ärger.', 'There was a lot of trouble with the landlord.'],
    ['die Enttäuschung', '-en', 'disappointment', 'Die Absage war eine große Enttäuschung.', 'The rejection was a big disappointment.'],
    ['die Überraschung', '-en', 'surprise', 'Die Party war eine gelungene Überraschung.', 'The party was a successful surprise.'],
    ['die Geduld', 'ohne Plural', 'patience', 'Beim Lernen braucht man vor allem Geduld.', 'When learning you mainly need patience.'],
    ['das Selbstbewusstsein', 'ohne Plural', 'self-confidence', 'Das Zertifikat hat mein Selbstbewusstsein gestärkt.', 'The certificate strengthened my self-confidence.'],
    ['die Eigenschaft', '-en', 'quality, characteristic', 'Ihre beste Eigenschaft ist ihre Ruhe.', 'Her best quality is her calm.'],
    ['der Charakter', '-e', 'character', 'Er hat einen sehr offenen Charakter.', 'He has a very open character.'],
    ['das Verständnis', 'ohne Plural', 'understanding, sympathy', 'Vielen Dank für Ihr Verständnis.', 'Thank you very much for your understanding.'],
    ['die Hoffnung', '-en', 'hope', 'Die Hoffnung habe ich nie aufgegeben.', 'I never gave up hope.'],
    ['der Mut', 'ohne Plural', 'courage', 'Es kostet Mut, in einer fremden Sprache zu reden.', 'It takes courage to speak in a foreign language.'],
  ],

  verbs: [
    ['sich freuen', null, 'to be pleased', 'Ich freue mich sehr über deine Zusage.', 'I am very pleased about your acceptance.'],
    ['sich ärgern', null, 'to be annoyed', 'Über die Verspätung habe ich mich geärgert.', 'I was annoyed about the delay.'],
    ['sich aufregen', null, 'to get worked up', 'Reg dich nicht auf, das lässt sich klären.', 'Do not get worked up, it can be sorted out.'],
    ['sich sorgen', null, 'to worry', 'Meine Mutter sorgt sich ständig um mich.', 'My mother worries about me constantly.'],
    ['sich schämen', null, 'to be ashamed', 'Am Anfang habe ich mich für meine Fehler geschämt.', 'At first I was ashamed of my mistakes.'],
    ['hoffen', null, 'to hope', 'Ich hoffe, dass es dir bald besser geht.', 'I hope you feel better soon.'],
    ['fürchten', null, 'to fear', 'Ich fürchte, das schaffe ich nicht rechtzeitig.', 'I fear I will not manage that in time.'],
    ['sich beruhigen', null, 'to calm down', 'Nach einer Stunde hat er sich beruhigt.', 'After an hour he calmed down.'],
    ['enttäuschen', null, 'to disappoint', 'Das Ergebnis hat mich enttäuscht.', 'The result disappointed me.'],
    ['überraschen', null, 'to surprise', 'Deine Antwort hat mich positiv überrascht.', 'Your answer surprised me positively.'],
    ['vermissen', null, 'to miss (someone)', 'Ich vermisse meine Familie besonders an Feiertagen.', 'I miss my family especially on holidays.'],
    ['sich gewöhnen an', null, 'to get used to', 'An das Wetter habe ich mich nie gewöhnt.', 'I never got used to the weather.'],
  ],

  adjectives: [
    ['zufrieden', null, 'satisfied, content', 'Mit dem Ergebnis bin ich sehr zufrieden.', 'I am very satisfied with the result.'],
    ['aufgeregt', null, 'nervous, excited', 'Vor dem Sprechen bin ich immer aufgeregt.', 'Before speaking I am always nervous.'],
    ['nervös', null, 'nervous', 'Sei nicht nervös, du kannst das.', 'Do not be nervous, you can do it.'],
    ['traurig', null, 'sad', 'Der Abschied war traurig, aber schön.', 'The farewell was sad but nice.'],
    ['stolz', null, 'proud', 'Ich bin stolz auf das, was ich gelernt habe.', 'I am proud of what I have learned.'],
    ['ehrlich', null, 'honest', 'Um ehrlich zu sein, war es zu schwer.', 'To be honest, it was too hard.'],
    ['geduldig', null, 'patient', 'Unsere Lehrerin ist unglaublich geduldig.', 'Our teacher is incredibly patient.'],
    ['hilfsbereit', null, 'helpful', 'Die Nachbarn sind alle sehr hilfsbereit.', 'The neighbours are all very helpful.'],
    ['zuversichtlich', null, 'confident, optimistic', 'Ich bin zuversichtlich, dass es klappt.', 'I am confident that it will work out.'],
    ['neugierig', null, 'curious', 'Kinder sind von Natur aus neugierig.', 'Children are naturally curious.'],
    ['gelassen', null, 'relaxed, composed', 'Mit den Jahren wird man gelassener.', 'Over the years you get more composed.'],
  ],

  phrases: [
    ['Angst haben vor', null, 'to be afraid of', 'Ich habe keine Angst mehr vor dem Sprechen.', 'I am no longer afraid of speaking.'],
    ['sich Sorgen machen', null, 'to worry', 'Mach dir bitte keine Sorgen um mich.', 'Please do not worry about me.'],
    ['gute Laune haben', null, 'to be in a good mood', 'Bei Sonne habe ich sofort gute Laune.', 'When the sun is out I am immediately in a good mood.'],
    ['Es tut mir leid.', null, 'I am sorry.', 'Es tut mir leid, dass ich mich nicht gemeldet habe.', 'I am sorry that I did not get in touch.'],
  ],
};
