export default {
  key: 'gesundheit',
  label: { de: 'Gesundheit & Körper', en: 'Health & body' },
  icon: '\u{1FA7A}',
  payoff: {
    de: 'Hören Teil 1 (Ansagen) und Sprechen: Arzttermin, Beschwerden, Krankmeldung.',
    en: 'Hören part 1 (announcements) and Sprechen: appointments, symptoms, sick notes.',
  },

  nouns: [
    ['die Gesundheit', 'ohne Plural', 'health', 'Nach der Kur geht es meiner Gesundheit besser.', 'After the treatment my health is better.'],
    ['die Krankheit', '-en', 'illness', 'Die Krankheit dauert meist eine Woche.', 'The illness usually lasts a week.'],
    ['die Beschwerde', '-n', 'complaint, symptom', 'Seit wann haben Sie diese Beschwerden?', 'Since when have you had these symptoms?'],
    ['die Schmerzen', 'nur Plural', 'pain', 'Ich habe seit gestern Schmerzen im Rücken.', 'I have had pain in my back since yesterday.'],
    ['das Fieber', 'ohne Plural', 'fever', 'Das Fieber ist auf 39 Grad gestiegen.', 'The fever has risen to 39 degrees.'],
    ['die Erkältung', '-en', 'cold', 'Bei einer Erkältung hilft vor allem Ruhe.', 'With a cold, rest helps most of all.'],
    ['der Husten', 'ohne Plural', 'cough', 'Der Husten hält schon drei Wochen an.', 'The cough has lasted three weeks already.'],
    ['die Grippe', 'ohne Plural', 'flu', 'Mit Grippe sollte man zu Hause bleiben.', 'With flu you should stay at home.'],
    ['die Praxis', 'Praxen', 'doctor’s practice', 'Die Praxis ist mittwochs nachmittags geschlossen.', 'The practice is closed on Wednesday afternoons.'],
    ['der Termin', '-e', 'appointment', 'Ich hätte gern einen Termin für nächste Woche.', 'I would like an appointment for next week.'],
    ['die Überweisung', '-en', 'referral', 'Für den Facharzt brauchen Sie eine Überweisung.', 'For the specialist you need a referral.'],
    ['das Rezept', '-e', 'prescription', 'Das Rezept können Sie in jeder Apotheke einlösen.', 'You can use the prescription at any pharmacy.'],
    ['die Apotheke', '-n', 'pharmacy', 'Die Apotheke am Bahnhof hat Notdienst.', 'The pharmacy at the station is on emergency duty.'],
    ['das Medikament', '-e', 'medicine, drug', 'Nehmen Sie das Medikament nach dem Essen.', 'Take the medicine after meals.'],
    ['die Krankenkasse', '-n', 'health insurance fund', 'Die Krankenkasse übernimmt die Kosten.', 'The health insurance fund covers the costs.'],
    ['die Krankenversicherung', '-en', 'health insurance', 'In Deutschland ist die Krankenversicherung Pflicht.', 'In Germany health insurance is compulsory.'],
    ['die Krankmeldung', '-en', 'sick note', 'Die Krankmeldung muss am dritten Tag beim Arbeitgeber sein.', 'The sick note must be with the employer on the third day.'],
    ['das Krankenhaus', '-¨er', 'hospital', 'Er lag vier Tage im Krankenhaus.', 'He was in hospital for four days.'],
    ['der Notruf', '-e', 'emergency call', 'Der Notruf in Deutschland ist die 112.', 'The emergency number in Germany is 112.'],
    ['die Untersuchung', '-en', 'examination, check-up', 'Die Untersuchung dauert nur zehn Minuten.', 'The examination only takes ten minutes.'],
    ['die Behandlung', '-en', 'treatment', 'Die Behandlung beginnt nächsten Monat.', 'The treatment starts next month.'],
    ['die Ernährung', 'ohne Plural', 'diet, nutrition', 'Eine ausgewogene Ernährung hilft dem Immunsystem.', 'A balanced diet helps the immune system.'],
    ['die Bewegung', 'ohne Plural', 'exercise, movement', 'Der Arzt hat mir mehr Bewegung empfohlen.', 'The doctor recommended more exercise to me.'],
    ['der Stress', 'ohne Plural', 'stress', 'Stress schlägt mir auf den Magen.', 'Stress upsets my stomach.'],
    ['der Rücken', '-', 'back', 'Vom langen Sitzen tut mir der Rücken weh.', 'My back hurts from sitting for a long time.'],
    ['der Magen', '-¨', 'stomach', 'Auf nüchternen Magen wirkt die Tablette schneller.', 'On an empty stomach the tablet works faster.'],
  ],

  verbs: [
    ['sich fühlen', null, 'to feel', 'Ich fühle mich heute viel besser.', 'I feel much better today.'],
    ['wehtun', 'tut weh · tat weh · hat wehgetan', 'to hurt', 'Mir tut der Hals weh.', 'My throat hurts.'],
    ['sich erkälten', null, 'to catch a cold', 'Im Zug habe ich mich erkältet.', 'I caught a cold on the train.'],
    ['untersuchen', null, 'to examine', 'Die Ärztin untersucht mich gleich.', 'The doctor will examine me shortly.'],
    ['behandeln', null, 'to treat', 'Die Entzündung wird mit Antibiotika behandelt.', 'The infection is treated with antibiotics.'],
    ['verschreiben', 'verschreibt · verschrieb · hat verschrieben', 'to prescribe', 'Der Arzt hat mir eine Salbe verschrieben.', 'The doctor prescribed me an ointment.'],
    ['einnehmen', 'nimmt ein · nahm ein · hat eingenommen', 'to take (medicine)', 'Nehmen Sie die Tropfen dreimal täglich ein.', 'Take the drops three times a day.'],
    ['sich ausruhen', null, 'to rest', 'Ruh dich ein paar Tage richtig aus.', 'Have a proper rest for a few days.'],
    ['sich erholen', null, 'to recover', 'Nach der Operation hat er sich schnell erholt.', 'After the operation he recovered quickly.'],
    ['husten', null, 'to cough', 'Bitte husten Sie in die Armbeuge.', 'Please cough into your elbow.'],
    ['sich verletzen', null, 'to injure oneself', 'Beim Fußball hat er sich am Knie verletzt.', 'He injured his knee playing football.'],
    ['vermeiden', 'vermeidet · vermied · hat vermieden', 'to avoid', 'Vermeiden Sie in den nächsten Tagen Sport.', 'Avoid sport for the next few days.'],
    ['zunehmen', 'nimmt zu · nahm zu · hat zugenommen', 'to put on weight, to increase', 'Im Winter nehme ich immer etwas zu.', 'In winter I always put on a bit of weight.'],
    ['abnehmen', 'nimmt ab · nahm ab · hat abgenommen', 'to lose weight, to decrease', 'Sie hat durch Radfahren fünf Kilo abgenommen.', 'She lost five kilos through cycling.'],
  ],

  adjectives: [
    ['krank', null, 'ill, sick', 'Mein Sohn ist seit Montag krank.', 'My son has been ill since Monday.'],
    ['gesund', null, 'healthy', 'Nach zwei Wochen war er wieder gesund.', 'After two weeks he was healthy again.'],
    ['müde', null, 'tired', 'Ich bin abends oft zu müde zum Lernen.', 'In the evening I am often too tired to study.'],
    ['schwanger', null, 'pregnant', 'Meine Schwester ist im fünften Monat schwanger.', 'My sister is five months pregnant.'],
    ['verletzt', null, 'injured', 'Zum Glück wurde niemand schwer verletzt.', 'Luckily nobody was seriously injured.'],
    ['ansteckend', null, 'contagious', 'Die ersten Tage sind besonders ansteckend.', 'The first few days are especially contagious.'],
    ['regelmäßig', null, 'regular', 'Regelmäßiger Sport senkt den Blutdruck.', 'Regular sport lowers blood pressure.'],
  ],

  phrases: [
    ['einen Termin vereinbaren', null, 'to make an appointment', 'Ich möchte einen Termin vereinbaren.', 'I would like to make an appointment.'],
    ['Gute Besserung!', null, 'Get well soon!', 'Gute Besserung und melde dich, wenn du etwas brauchst.', 'Get well soon and get in touch if you need anything.'],
    ['sich krankschreiben lassen', null, 'to get signed off sick', 'Ich habe mich für drei Tage krankschreiben lassen.', 'I got signed off sick for three days.'],
    ['Was fehlt Ihnen?', null, 'What is wrong? (doctor to patient)', '"Was fehlt Ihnen?" – "Ich habe starke Kopfschmerzen."', '"What is wrong?" – "I have a bad headache."'],
  ],
};
