export default {
  key: 'konnektoren',
  label: { de: 'Konnektoren & Textbau', en: 'Connectors & text structure' },
  icon: '\u{1F9F5}',
  payoff: {
    de: 'Der Unterschied zwischen A2 und B1 im Schreiben: Sätze verbinden.',
    en: 'The difference between A2 and B1 in writing: joining sentences up.',
  },

  connectors: [
    ['weil', null, 'because (verb to the end)', 'Ich komme später, weil ich noch arbeiten muss.', 'I am coming later because I still have to work.'],
    ['denn', null, 'because (normal word order)', 'Ich komme später, denn ich muss noch arbeiten.', 'I am coming later, because I still have to work.'],
    ['deshalb', null, 'therefore, that is why', 'Der Zug fiel aus, deshalb kam ich zu spät.', 'The train was cancelled, that is why I was late.'],
    ['trotzdem', null, 'nevertheless', 'Es regnete, trotzdem sind wir gelaufen.', 'It was raining, nevertheless we walked.'],
    ['obwohl', null, 'although', 'Obwohl es teuer war, habe ich es gekauft.', 'Although it was expensive, I bought it.'],
    ['damit', null, 'so that (purpose)', 'Ich lerne täglich, damit ich die Prüfung bestehe.', 'I study daily so that I pass the exam.'],
    ['um … zu', null, 'in order to', 'Ich lerne täglich, um die Prüfung zu bestehen.', 'I study daily in order to pass the exam.'],
    ['wenn', null, 'if, whenever', 'Wenn ich Zeit habe, koche ich selbst.', 'When I have time I cook myself.'],
    ['als', null, 'when (single past event)', 'Als ich ankam, war niemand da.', 'When I arrived nobody was there.'],
    ['falls', null, 'in case, if', 'Falls es regnet, bleiben wir zu Hause.', 'In case it rains we will stay at home.'],
    ['sobald', null, 'as soon as', 'Ich melde mich, sobald ich mehr weiß.', 'I will get in touch as soon as I know more.'],
    ['seitdem', null, 'since (time)', 'Seitdem ich hier wohne, fahre ich Rad.', 'Since I have lived here I cycle.'],
    ['bevor', null, 'before', 'Bevor du unterschreibst, lies alles.', 'Before you sign, read everything.'],
    ['nachdem', null, 'after (with Plusquamperfekt)', 'Nachdem ich gegessen hatte, ging ich los.', 'After I had eaten I set off.'],
    ['während', null, 'while, whereas', 'Während ich koche, deckt er den Tisch.', 'While I cook he sets the table.'],
    ['bis', null, 'until', 'Warte bitte, bis ich fertig bin.', 'Please wait until I am finished.'],
    ['dass', null, 'that (verb to the end)', 'Ich hoffe, dass alles klappt.', 'I hope that everything works out.'],
    ['ob', null, 'whether', 'Ich weiß nicht, ob er kommt.', 'I do not know whether he is coming.'],
    ['sowohl … als auch', null, 'both … and', 'Sie spricht sowohl Deutsch als auch Polnisch.', 'She speaks both German and Polish.'],
    ['entweder … oder', null, 'either … or', 'Entweder wir fahren heute oder gar nicht.', 'Either we go today or not at all.'],
    ['weder … noch', null, 'neither … nor', 'Ich habe weder Zeit noch Lust.', 'I have neither the time nor the inclination.'],
    ['nicht nur … sondern auch', null, 'not only … but also', 'Das ist nicht nur billig, sondern auch praktisch.', 'That is not only cheap but also practical.'],
    ['zwar … aber', null, 'admittedly … but', 'Es ist zwar weit, aber schön.', 'It is far, admittedly, but beautiful.'],
    ['je … desto', null, 'the … the', 'Je öfter du übst, desto leichter wird es.', 'The more often you practise, the easier it gets.'],
    ['außerdem', null, 'besides, moreover', 'Es ist spät. Außerdem bin ich müde.', 'It is late. Besides, I am tired.'],
    ['jedoch', null, 'however', 'Der Preis ist gut, jedoch fehlt ein Balkon.', 'The price is good, however there is no balcony.'],
    ['allerdings', null, 'admittedly, though', 'Das Zimmer ist schön, allerdings sehr klein.', 'The room is nice, though very small.'],
    ['zunächst', null, 'first of all', 'Zunächst möchte ich mich vorstellen.', 'First of all I would like to introduce myself.'],
    ['zusammenfassend', null, 'in summary', 'Zusammenfassend lässt sich sagen, dass beides funktioniert.', 'In summary it can be said that both work.'],
    ['einerseits', null, 'on the one hand', 'Einerseits spare ich Geld, andererseits Zeit.', 'On the one hand I save money, on the other time.'],
    ['dagegen', null, 'by contrast', 'Im Sommer ist es voll, im Winter dagegen leer.', 'In summer it is full, in winter by contrast empty.'],
    ['nämlich', null, 'namely, you see', 'Ich kann nicht, ich arbeite nämlich.', 'I cannot, you see I am working.'],
    ['sonst', null, 'otherwise', 'Beeil dich, sonst verpassen wir den Zug.', 'Hurry up, otherwise we will miss the train.'],
    ['statt … zu', null, 'instead of doing', 'Statt zu diskutieren, sollten wir handeln.', 'Instead of discussing we should act.'],
    ['ohne … zu', null, 'without doing', 'Er ging, ohne sich zu verabschieden.', 'He left without saying goodbye.'],
  ],

  phrases: [
    ['Liebe Grüße', null, 'Kind regards (informal)', 'Bis bald und liebe Grüße, Amir', 'See you soon and kind regards, Amir'],
    ['Mit freundlichen Grüßen', null, 'Yours sincerely (formal)', 'Mit freundlichen Grüßen, Amir Hosseini', 'Yours sincerely, Amir Hosseini'],
    ['Ich schreibe Ihnen, weil …', null, 'I am writing to you because …', 'Ich schreibe Ihnen, weil ich den Kurs verschieben möchte.', 'I am writing to you because I would like to postpone the course.'],
    ['Vielen Dank im Voraus', null, 'Many thanks in advance', 'Vielen Dank im Voraus für Ihre Mühe.', 'Many thanks in advance for your trouble.'],
    ['Ich würde mich freuen, wenn …', null, 'I would be glad if …', 'Ich würde mich freuen, wenn Sie mir antworten könnten.', 'I would be glad if you could reply to me.'],
  ],
};
