export default {
  key: 'nomenverben',
  label: { de: 'Feste Wendungen', en: 'Fixed expressions' },
  icon: '\u{1F9E9}',
  payoff: {
    de: 'Nomen-Verb-Verbindungen: erwachsenes Deutsch statt Schulbuchdeutsch.',
    en: 'Noun-verb collocations: grown-up German instead of textbook German.',
  },

  phrases: [
    ['eine Entscheidung treffen', null, 'to make a decision', 'Die Entscheidung müssen wir heute treffen.', 'We have to make the decision today.'],
    ['eine Frage stellen', null, 'to ask a question', 'Darf ich eine Frage stellen?', 'May I ask a question?'],
    ['eine Rolle spielen', null, 'to play a part, to matter', 'Das Geld spielt hier keine Rolle.', 'The money does not matter here.'],
    ['in Frage kommen', null, 'to be an option', 'Ein Umzug kommt für mich nicht in Frage.', 'Moving is not an option for me.'],
    ['zur Verfügung stehen', null, 'to be available', 'Für Rückfragen stehe ich gern zur Verfügung.', 'I am happy to be available for questions.'],
    ['in Kontakt treten', null, 'to get in contact', 'Bitte treten Sie mit der Schule in Kontakt.', 'Please get in contact with the school.'],
    ['Rücksprache halten', null, 'to consult', 'Ich halte kurz Rücksprache mit meinem Chef.', 'I will quickly consult my boss.'],
    ['eine Rolle übernehmen', null, 'to take on a role', 'Sie hat die Rolle der Sprecherin übernommen.', 'She took on the role of spokesperson.'],
    ['Kritik üben', null, 'to voice criticism', 'Die Mieter übten scharfe Kritik.', 'The tenants voiced sharp criticism.'],
    ['Abschied nehmen', null, 'to say goodbye', 'Am Bahnhof nahmen wir Abschied.', 'We said goodbye at the station.'],
    ['Bescheid wissen', null, 'to be in the know', 'Über die neuen Regeln weiß ich Bescheid.', 'I am in the know about the new rules.'],
    ['einen Termin wahrnehmen', null, 'to keep an appointment', 'Ich kann den Termin leider nicht wahrnehmen.', 'Unfortunately I cannot keep the appointment.'],
    ['Verantwortung übernehmen', null, 'to take responsibility', 'Er übernimmt Verantwortung für das Team.', 'He takes responsibility for the team.'],
    ['sich Mühe geben', null, 'to make an effort', 'Sie hat sich große Mühe gegeben.', 'She made a big effort.'],
    ['einen Vorschlag machen', null, 'to make a suggestion', 'Darf ich einen Vorschlag machen?', 'May I make a suggestion?'],
    ['zum Ausdruck bringen', null, 'to express', 'Damit möchte ich meinen Dank zum Ausdruck bringen.', 'With this I would like to express my thanks.'],
    ['in Anspruch nehmen', null, 'to make use of, to claim', 'Diese Beratung können Sie kostenlos in Anspruch nehmen.', 'You can make use of this advice free of charge.'],
    ['Schritte unternehmen', null, 'to take steps', 'Die Gemeinde unternimmt erste Schritte.', 'The municipality is taking first steps.'],
    ['einen Eindruck machen', null, 'to make an impression', 'Die Wohnung hat einen guten Eindruck gemacht.', 'The flat made a good impression.'],
    ['Erfahrungen sammeln', null, 'to gain experience', 'Im Praktikum sammle ich Erfahrungen.', 'I am gaining experience in the internship.'],
    ['Gebrauch machen von', null, 'to make use of', 'Davon habe ich noch keinen Gebrauch gemacht.', 'I have not yet made use of that.'],
    ['ums Leben kommen', null, 'to lose one’s life', 'Bei dem Unfall kam zum Glück niemand ums Leben.', 'Luckily nobody lost their life in the accident.'],
    ['auf die Nerven gehen', null, 'to get on someone’s nerves', 'Der Lärm geht mir auf die Nerven.', 'The noise gets on my nerves.'],
    ['eine Ausnahme machen', null, 'to make an exception', 'Dieses Mal machen wir eine Ausnahme.', 'This time we will make an exception.'],
    ['im Voraus', null, 'in advance', 'Die Miete zahlt man im Voraus.', 'The rent is paid in advance.'],
    ['in der Regel', null, 'as a rule', 'In der Regel dauert das zwei Wochen.', 'As a rule that takes two weeks.'],
    ['auf jeden Fall', null, 'in any case, definitely', 'Ich komme auf jeden Fall.', 'I am definitely coming.'],
    ['auf keinen Fall', null, 'under no circumstances', 'Das mache ich auf keinen Fall.', 'I will not do that under any circumstances.'],
    ['vor allem', null, 'above all', 'Mir fehlt vor allem das Sprechen.', 'What I lack above all is speaking practice.'],
    ['zum Schluss', null, 'finally, at the end', 'Zum Schluss möchte ich mich bedanken.', 'Finally I would like to say thank you.'],
    ['im Großen und Ganzen', null, 'by and large', 'Im Großen und Ganzen bin ich zufrieden.', 'By and large I am satisfied.'],
    ['es geht um', null, 'it is about', 'In dem Text geht es um Mülltrennung.', 'The text is about waste separation.'],
    ['es handelt sich um', null, 'it is a case of', 'Es handelt sich um eine einmalige Zahlung.', 'It is a case of a one-off payment.'],
    ['Wert darauf legen, dass', null, 'to care that', 'Ich lege Wert darauf, dass alle mitreden.', 'I care that everyone has a say.'],
  ],
};
