export default {
  key: 'praepositionen',
  label: { de: 'Verben mit Präposition', en: 'Verbs with prepositions' },
  icon: '\u{1F517}',
  payoff: {
    de: 'Der häufigste Fehler auf B1 - und in telc-Sprachbausteinen fast garantiert.',
    en: 'The most common B1 mistake - and almost guaranteed in telc Sprachbausteine.',
  },

  verbs: [
    ['warten auf + Akk.', null, 'to wait for', 'Ich warte seit einer Stunde auf den Bus.', 'I have been waiting for the bus for an hour.'],
    ['sich freuen auf + Akk.', null, 'to look forward to', 'Ich freue mich auf das Wochenende.', 'I am looking forward to the weekend.'],
    ['sich freuen über + Akk.', null, 'to be pleased about', 'Sie freut sich über das Geschenk.', 'She is pleased about the present.'],
    ['sich interessieren für + Akk.', null, 'to be interested in', 'Er interessiert sich für Politik.', 'He is interested in politics.'],
    ['sich kümmern um + Akk.', null, 'to take care of', 'Ich kümmere mich um die Anmeldung.', 'I will take care of the registration.'],
    ['sich bewerben um + Akk.', null, 'to apply for', 'Sie bewirbt sich um eine Stelle als Erzieherin.', 'She is applying for a position as a nursery teacher.'],
    ['sich erinnern an + Akk.', null, 'to remember', 'Erinnerst du dich an unseren ersten Kurs?', 'Do you remember our first course?'],
    ['denken an + Akk.', null, 'to think of', 'Denk bitte an die Unterlagen.', 'Please think of the documents.'],
    ['sich gewöhnen an + Akk.', null, 'to get used to', 'An das frühe Aufstehen gewöhnt man sich.', 'You get used to getting up early.'],
    ['teilnehmen an + Dat.', null, 'to take part in', 'Er nimmt an dem Wettbewerb teil.', 'He is taking part in the competition.'],
    ['sich beteiligen an + Dat.', null, 'to participate in', 'Viele beteiligen sich an der Aktion.', 'Many people participate in the campaign.'],
    ['leiden unter + Dat.', null, 'to suffer from', 'Viele leiden unter dem Lärm.', 'Many people suffer from the noise.'],
    ['bestehen aus + Dat.', null, 'to consist of', 'Die Prüfung besteht aus vier Teilen.', 'The exam consists of four parts.'],
    ['sich handeln um + Akk.', null, 'to be a matter of', 'Es handelt sich um einen Irrtum.', 'It is a matter of an error.'],
    ['gehören zu + Dat.', null, 'to be part of, to belong to', 'Fehler gehören zum Lernen.', 'Mistakes are part of learning.'],
    ['sich verlassen auf + Akk.', null, 'to rely on', 'Auf ihn kann man sich verlassen.', 'You can rely on him.'],
    ['sich beschweren über + Akk.', null, 'to complain about', 'Sie beschwerte sich über den Lärm.', 'She complained about the noise.'],
    ['sich ärgern über + Akk.', null, 'to be annoyed about', 'Ich ärgere mich über den Fehler.', 'I am annoyed about the mistake.'],
    ['sich streiten über + Akk.', null, 'to argue about', 'Wir streiten uns über Kleinigkeiten.', 'We argue about small things.'],
    ['sich entscheiden für + Akk.', null, 'to decide in favour of', 'Wir haben uns für die kleinere Wohnung entschieden.', 'We decided in favour of the smaller flat.'],
    ['sich bedanken für + Akk.', null, 'to thank for', 'Ich bedanke mich für Ihre Hilfe.', 'I thank you for your help.'],
    ['sich entschuldigen für + Akk.', null, 'to apologise for', 'Er entschuldigte sich für die Verspätung.', 'He apologised for the delay.'],
    ['bitten um + Akk.', null, 'to ask for', 'Ich bitte um eine kurze Antwort.', 'I ask for a brief reply.'],
    ['sprechen über + Akk.', null, 'to talk about', 'Wir sprechen morgen über das Projekt.', 'We will talk about the project tomorrow.'],
    ['sprechen mit + Dat.', null, 'to talk to', 'Sprich bitte mit deinem Chef.', 'Please talk to your boss.'],
    ['sich informieren über + Akk.', null, 'to get information about', 'Informieren Sie sich über die Fristen.', 'Get information about the deadlines.'],
    ['sich vorbereiten auf + Akk.', null, 'to prepare for', 'Ich bereite mich auf die Prüfung vor.', 'I am preparing for the exam.'],
    ['achten auf + Akk.', null, 'to pay attention to', 'Achten Sie auf die Aussprache.', 'Pay attention to the pronunciation.'],
    ['sich konzentrieren auf + Akk.', null, 'to concentrate on', 'Konzentriere dich zuerst auf das Hören.', 'Concentrate on listening first.'],
    ['abhängen von + Dat.', null, 'to depend on', 'Das hängt vom Wetter ab.', 'That depends on the weather.'],
    ['sich verabreden mit + Dat.', null, 'to arrange to meet', 'Ich habe mich mit Lena verabredet.', 'I have arranged to meet Lena.'],
    ['sich verlieben in + Akk.', null, 'to fall in love with', 'Er hat sich in die Stadt verliebt.', 'He fell in love with the city.'],
    ['sich unterhalten über + Akk.', null, 'to converse about', 'Wir haben uns lange über die Arbeit unterhalten.', 'We talked about work for a long time.'],
    ['schützen vor + Dat.', null, 'to protect from', 'Die Impfung schützt vor schweren Verläufen.', 'The vaccination protects against severe cases.'],
    ['Angst haben vor + Dat.', null, 'to be afraid of', 'Er hat Angst vor Prüfungen.', 'He is afraid of exams.'],
    ['zufrieden sein mit + Dat.', null, 'to be satisfied with', 'Ich bin mit dem Ergebnis zufrieden.', 'I am satisfied with the result.'],
    ['einverstanden sein mit + Dat.', null, 'to agree with', 'Bist du mit dem Termin einverstanden?', 'Do you agree with the date?'],
    ['stolz sein auf + Akk.', null, 'to be proud of', 'Ich bin stolz auf meine Kinder.', 'I am proud of my children.'],
    ['verantwortlich sein für + Akk.', null, 'to be responsible for', 'Wer ist für die Kasse verantwortlich?', 'Who is responsible for the till?'],
    ['sich eignen für + Akk.', null, 'to be suitable for', 'Der Kurs eignet sich für Anfänger.', 'The course is suitable for beginners.'],
    ['sich beziehen auf + Akk.', null, 'to refer to', 'Ich beziehe mich auf Ihr Schreiben vom 3. Mai.', 'I refer to your letter of 3 May.'],
    ['rechnen mit + Dat.', null, 'to reckon with, to expect', 'Wir rechnen mit 50 Gästen.', 'We are expecting 50 guests.'],
    ['sich wundern über + Akk.', null, 'to be surprised at', 'Ich wundere mich über seine Reaktion.', 'I am surprised at his reaction.'],
    ['sich sehnen nach + Dat.', null, 'to long for', 'Im Winter sehne ich mich nach Sonne.', 'In winter I long for sun.'],
    ['fragen nach + Dat.', null, 'to ask about', 'Er fragte nach dem Weg zum Bahnhof.', 'He asked the way to the station.'],
    ['suchen nach + Dat.', null, 'to search for', 'Wir suchen seit Monaten nach einer Wohnung.', 'We have been searching for a flat for months.'],
    ['sich anmelden für + Akk.', null, 'to sign up for', 'Melde dich für den Kurs an.', 'Sign up for the course.'],
    ['sich bemühen um + Akk.', null, 'to make an effort for', 'Sie bemüht sich um einen Ausbildungsplatz.', 'She is making an effort to get a training place.'],
  ],
};
