export default {
  key: 'verben',
  label: { de: 'Wichtige Verben', en: 'Key verbs' },
  icon: '⚡',
  payoff: {
    de: 'Die unregelmäßigen Formen, die in jedem Prüfungsteil vorkommen.',
    en: 'The irregular forms that turn up in every part of the exam.',
  },

  verbs: [
    ['beginnen', 'beginnt · begann · hat begonnen', 'to begin', 'Der Kurs begann im September.', 'The course began in September.'],
    ['bekommen', 'bekommt · bekam · hat bekommen', 'to get, to receive', 'Gestern habe ich die Zusage bekommen.', 'Yesterday I got the acceptance.'],
    ['beschließen', 'beschließt · beschloss · hat beschlossen', 'to decide', 'Wir haben beschlossen, umzuziehen.', 'We decided to move house.'],
    ['bitten', 'bittet · bat · hat gebeten', 'to ask, to request', 'Er bat mich um Hilfe.', 'He asked me for help.'],
    ['bleiben', 'bleibt · blieb · ist geblieben', 'to stay', 'Ich bin bis Sonntag geblieben.', 'I stayed until Sunday.'],
    ['bringen', 'bringt · brachte · hat gebracht', 'to bring', 'Sie hat Kuchen mitgebracht.', 'She brought cake along.'],
    ['denken', 'denkt · dachte · hat gedacht', 'to think', 'Ich dachte, du kommst später.', 'I thought you were coming later.'],
    ['entscheiden', 'entscheidet · entschied · hat entschieden', 'to decide', 'Das muss jeder selbst entscheiden.', 'Everyone has to decide that for themselves.'],
    ['erfahren', 'erfährt · erfuhr · hat erfahren', 'to find out', 'Von der Absage habe ich erst gestern erfahren.', 'I only found out about the rejection yesterday.'],
    ['fallen', 'fällt · fiel · ist gefallen', 'to fall', 'Die Preise sind zuletzt gefallen.', 'Prices have fallen recently.'],
    ['finden', 'findet · fand · hat gefunden', 'to find, to think', 'Ich finde den Vorschlag gut.', 'I think the suggestion is good.'],
    ['geben', 'gibt · gab · hat gegeben', 'to give', 'Gib mir bitte kurz Bescheid.', 'Please let me know briefly.'],
    ['gehören', null, 'to belong', 'Das Fahrrad gehört meiner Schwester.', 'The bicycle belongs to my sister.'],
    ['gelingen', 'gelingt · gelang · ist gelungen', 'to succeed, to work out', 'Der Kuchen ist mir gut gelungen.', 'The cake turned out well for me.'],
    ['gelten', 'gilt · galt · hat gegolten', 'to be valid, to apply', 'Die Regel gilt für alle Mieter.', 'The rule applies to all tenants.'],
    ['geschehen', 'geschieht · geschah · ist geschehen', 'to happen', 'Was ist hier geschehen?', 'What happened here?'],
    ['halten', 'hält · hielt · hat gehalten', 'to hold, to stop', 'Der Zug hält hier nicht.', 'The train does not stop here.'],
    ['heben', 'hebt · hob · hat gehoben', 'to lift, to raise', 'Schwere Kisten hebt man mit den Beinen.', 'You lift heavy boxes with your legs.'],
    ['helfen', 'hilft · half · hat geholfen', 'to help', 'Kannst du mir kurz helfen?', 'Can you help me briefly?'],
    ['kennen', 'kennt · kannte · hat gekannt', 'to know (be familiar with)', 'Ich kenne sie seit der Schulzeit.', 'I have known her since school.'],
    ['lassen', 'lässt · ließ · hat gelassen', 'to let, to have done', 'Ich lasse das Auto reparieren.', 'I am having the car repaired.'],
    ['laufen', 'läuft · lief · ist gelaufen', 'to run, to walk, to be on', 'Der Film läuft noch bis Freitag.', 'The film is on until Friday.'],
    ['leihen', 'leiht · lieh · hat geliehen', 'to lend, to borrow', 'Kannst du mir dein Rad leihen?', 'Can you lend me your bike?'],
    ['liegen', 'liegt · lag · hat gelegen', 'to lie, to be situated', 'Das Dorf liegt an einem See.', 'The village lies by a lake.'],
    ['nehmen', 'nimmt · nahm · hat genommen', 'to take', 'Nimm besser die Bahn.', 'Better take the train.'],
    ['nennen', 'nennt · nannte · hat genannt', 'to name, to call', 'Nennen Sie bitte ein Beispiel.', 'Please name an example.'],
    ['raten', 'rät · riet · hat geraten', 'to advise, to guess', 'Ich rate dir, früher anzufangen.', 'I advise you to start earlier.'],
    ['schaffen', null, 'to manage, to achieve', 'Das schaffst du auch in zwei Monaten.', 'You can manage that in two months too.'],
    ['scheinen', 'scheint · schien · hat geschienen', 'to seem, to shine', 'Er scheint zufrieden zu sein.', 'He seems to be satisfied.'],
    ['schlagen', 'schlägt · schlug · hat geschlagen', 'to hit, to beat', 'Sie schlug einen Kompromiss vor.', 'She proposed a compromise.'],
    ['schneiden', 'schneidet · schnitt · hat geschnitten', 'to cut', 'Schneide das Gemüse klein.', 'Cut the vegetables small.'],
    ['sitzen', 'sitzt · saß · hat gesessen', 'to sit', 'Wir saßen zwei Stunden im Wartezimmer.', 'We sat in the waiting room for two hours.'],
    ['sprechen', 'spricht · sprach · hat gesprochen', 'to speak', 'Ich sprach gestern mit dem Vermieter.', 'I spoke with the landlord yesterday.'],
    ['stehen', 'steht · stand · hat gestanden', 'to stand, to say (in a text)', 'Im Vertrag steht etwas anderes.', 'The contract says something different.'],
    ['steigen', 'steigt · stieg · ist gestiegen', 'to rise, to climb', 'Die Mieten sind stark gestiegen.', 'Rents have risen sharply.'],
    ['tragen', 'trägt · trug · hat getragen', 'to carry, to wear', 'Bei der Arbeit trage ich Sicherheitsschuhe.', 'At work I wear safety shoes.'],
    ['treffen', 'trifft · traf · hat getroffen', 'to meet, to hit', 'Wir treffen eine Entscheidung am Montag.', 'We will make a decision on Monday.'],
    ['verbringen', 'verbringt · verbrachte · hat verbracht', 'to spend (time)', 'Den Sommer verbrachten wir am Meer.', 'We spent the summer by the sea.'],
    ['vergessen', 'vergisst · vergaß · hat vergessen', 'to forget', 'Ich habe den Termin völlig vergessen.', 'I completely forgot the appointment.'],
    ['wachsen', 'wächst · wuchs · ist gewachsen', 'to grow', 'Die Stadt ist schnell gewachsen.', 'The city has grown quickly.'],
    ['werfen', 'wirft · warf · hat geworfen', 'to throw', 'Wirf die Verpackung in die gelbe Tonne.', 'Throw the packaging in the yellow bin.'],
    ['ziehen', 'zieht · zog · hat gezogen', 'to pull, to move', 'Zieh bitte die Tür zu.', 'Please pull the door shut.'],
    ['zwingen', 'zwingt · zwang · hat gezwungen', 'to force', 'Niemand zwingt dich dazu.', 'Nobody is forcing you to do it.'],
  ],
};
