export default {
  key: 'wohnen',
  label: { de: 'Wohnen & Zuhause', en: 'Housing & home' },
  icon: '\u{1F3E0}',
  payoff: {
    de: 'Lesen Teil 3 (Anzeigen) und Schreiben: Wohnungssuche, Nachbarn, Vermieter.',
    en: 'Lesen part 3 (adverts) and Schreiben: flat hunting, neighbours, landlords.',
  },

  nouns: [
    ['die Wohnung', '-en', 'flat, apartment', 'Wir suchen eine Wohnung mit drei Zimmern.', 'We are looking for a three-room flat.'],
    ['die Miete', '-n', 'rent', 'Die Miete ist am dritten Werktag fällig.', 'The rent is due on the third working day.'],
    ['die Nebenkosten', 'nur Plural', 'service charges, utilities', 'Die Nebenkosten sind in der Warmmiete enthalten.', 'The service charges are included in the rent.'],
    ['die Kaution', '-en', 'deposit', 'Die Kaution beträgt drei Kaltmieten.', 'The deposit is three months’ basic rent.'],
    ['der Mietvertrag', '-¨e', 'tenancy agreement', 'Lies den Mietvertrag, bevor du unterschreibst.', 'Read the tenancy agreement before you sign.'],
    ['der Vermieter', '-', 'landlord', 'Der Vermieter hat die Heizung reparieren lassen.', 'The landlord had the heating repaired.'],
    ['der Mieter', '-', 'tenant', 'Als Mieter hast du viele Rechte.', 'As a tenant you have a lot of rights.'],
    ['die Hausordnung', '-en', 'house rules', 'Laut Hausordnung ist ab 22 Uhr Ruhe.', 'According to the house rules it is quiet from 10 p.m.'],
    ['der Hausmeister', '-', 'caretaker, janitor', 'Bei einem Wasserschaden rufst du den Hausmeister.', 'If there is water damage you call the caretaker.'],
    ['der Umzug', '-¨e', 'move, removal', 'Der Umzug hat den ganzen Samstag gedauert.', 'The move took the whole Saturday.'],
    ['das Möbelstück', '-e', 'piece of furniture', 'Das einzige teure Möbelstück ist das Sofa.', 'The only expensive piece of furniture is the sofa.'],
    ['die Einrichtung', '-en', 'furnishings, fittings', 'Die Einrichtung ist alt, aber gemütlich.', 'The furnishings are old but cosy.'],
    ['der Stock', '-¨e', 'floor, storey', 'Wir wohnen im dritten Stock ohne Aufzug.', 'We live on the third floor with no lift.'],
    ['der Balkon', '-e', 'balcony', 'Im Sommer frühstücken wir auf dem Balkon.', 'In summer we have breakfast on the balcony.'],
    ['der Keller', '-', 'cellar, basement', 'Die Fahrräder stehen im Keller.', 'The bikes are in the cellar.'],
    ['die Heizung', '-en', 'heating', 'Die Heizung funktioniert seit gestern nicht.', 'The heating has not worked since yesterday.'],
    ['der Strom', 'ohne Plural', 'electricity', 'Der Strom wird einmal im Jahr abgerechnet.', 'Electricity is billed once a year.'],
    ['der Mangel', '-¨', 'defect, fault', 'Melde den Mangel schriftlich beim Vermieter.', 'Report the defect to the landlord in writing.'],
    ['die Wohngemeinschaft', '-en', 'shared flat, flatshare', 'In der Wohngemeinschaft kocht jeder einmal pro Woche.', 'In the flatshare everyone cooks once a week.'],
    ['der Lärm', 'ohne Plural', 'noise', 'Der Lärm von der Baustelle beginnt um sieben.', 'The noise from the building site starts at seven.'],
    ['die Besichtigung', '-en', 'viewing', 'Zur Besichtigung kamen vierzig Leute.', 'Forty people came to the viewing.'],
    ['die Kündigung', '-en', 'notice, termination', 'Die Kündigung muss drei Monate vorher da sein.', 'The notice has to arrive three months in advance.'],
    ['die Nachbarschaft', '-en', 'neighbourhood', 'Die Nachbarschaft ist ruhig und grün.', 'The neighbourhood is quiet and green.'],
  ],

  verbs: [
    ['mieten', null, 'to rent (as tenant)', 'Wir mieten die Wohnung ab dem ersten Mai.', 'We are renting the flat from the first of May.'],
    ['vermieten', null, 'to rent out, to let', 'Sie vermietet ein Zimmer an Studenten.', 'She rents out a room to students.'],
    ['umziehen', 'zieht um · zog um · ist umgezogen', 'to move house', 'Nächsten Monat ziehen wir nach Bremen um.', 'Next month we are moving to Bremen.'],
    ['einziehen', 'zieht ein · zog ein · ist eingezogen', 'to move in', 'Wir sind am Wochenende eingezogen.', 'We moved in at the weekend.'],
    ['ausziehen', 'zieht aus · zog aus · ist ausgezogen', 'to move out', 'Der Vormieter ist letzte Woche ausgezogen.', 'The previous tenant moved out last week.'],
    ['renovieren', null, 'to renovate, to decorate', 'Vor dem Auszug müssen wir renovieren.', 'Before moving out we have to redecorate.'],
    ['reparieren', null, 'to repair', 'Der Vermieter lässt das Fenster reparieren.', 'The landlord is having the window repaired.'],
    ['kündigen', null, 'to give notice, to terminate', 'Ich habe den Mietvertrag zum 30. Juni gekündigt.', 'I gave notice on the tenancy for 30 June.'],
    ['anmelden', null, 'to register (an address)', 'Nach dem Umzug musst du dich beim Bürgeramt anmelden.', 'After moving you have to register at the citizens’ office.'],
    ['einrichten', null, 'to furnish, to set up', 'Wir haben das Kinderzimmer neu eingerichtet.', 'We have refurnished the children’s room.'],
    ['aufräumen', null, 'to tidy up', 'Räum bitte vor der Besichtigung auf.', 'Please tidy up before the viewing.'],
    ['putzen', null, 'to clean', 'Das Treppenhaus putzt jede Partei abwechselnd.', 'Each household cleans the stairwell in turn.'],
    ['besichtigen', null, 'to view, to look round', 'Wir besichtigen die Wohnung am Donnerstag.', 'We are viewing the flat on Thursday.'],
  ],

  adjectives: [
    ['möbliert', null, 'furnished', 'Das Zimmer ist möbliert und sofort frei.', 'The room is furnished and available immediately.'],
    ['gemütlich', null, 'cosy', 'Die Küche ist klein, aber gemütlich.', 'The kitchen is small but cosy.'],
    ['ruhig', null, 'quiet', 'Die Lage ist ruhig, obwohl sie zentral ist.', 'The location is quiet although it is central.'],
    ['zentral', null, 'central', 'Zentral wohnen kostet hier viel Geld.', 'Living centrally costs a lot of money here.'],
    ['renoviert', null, 'renovated', 'Das Bad wurde letztes Jahr komplett renoviert.', 'The bathroom was completely renovated last year.'],
    ['geräumig', null, 'spacious', 'Die Wohnung ist hell und geräumig.', 'The flat is bright and spacious.'],
    ['sauber', null, 'clean', 'Das Treppenhaus ist immer sauber.', 'The stairwell is always clean.'],
    ['günstig', null, 'cheap, good value', 'Für diese Lage ist die Miete günstig.', 'For this location the rent is good value.'],
  ],

  phrases: [
    ['auf Wohnungssuche sein', null, 'to be flat hunting', 'Ich bin seit vier Monaten auf Wohnungssuche.', 'I have been flat hunting for four months.'],
    ['Rücksicht nehmen', null, 'to be considerate', 'Nach 22 Uhr nehmen wir Rücksicht auf die Nachbarn.', 'After 10 p.m. we are considerate towards the neighbours.'],
    ['die Miete überweisen', null, 'to transfer the rent', 'Die Miete überweise ich am Ersten jedes Monats.', 'I transfer the rent on the first of each month.'],
    ['in zentraler Lage', null, 'in a central location', 'Gesucht: 2 Zimmer in zentraler Lage.', 'Wanted: two rooms in a central location.'],
  ],
};
